
matrix:
  include:
    - language: go
      dist: trusty
      go: 
        - 1.13
      go_import_path: github.com/mirroraculous/mirroraculous
      before_install:
        - go get github.com/rs/xid
        - go get github.com/gin-gonic/gin
        - go get github.com/dgrijalva/jwt-go
        - go get github.com/gin-contrib/cors 
      addons:
        sonarcloud:
          organization: "mirroraculous"
          token:
            secure: ${SONAR_TOKEN}
      script:
        - go test -v -json ./... > report.json
        - go test -cover -coverprofile=coverage.out ./...
        - sonar-scanner

    - language: node_js
      dist: trusty
      node_js:
        - 10.15
      addons:
        sonarcloud:
          organization: "mirroraculous"
          token:
            secure: ${SONAR_TOKEN}

        chrome: stable
      # go:
      #   -1.13
      cache:
        directories:
          - ./node_modules
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - npm install -g @angular/cli
      install:
        # - go version
        # - go get ./...
        - npm install
        - npm install sonar-scanner --save-dev
        - npm install rxjs-compat --save

      script:
        # - go run main.go
        - ng test --watch=false --code-coverage
        - sonar-scanner
