dist: trusty

language: go

go: 
- 1.13

go_import_path: github.com/mirroraculous/mirroraculous

addons:
  sonarcloud:
    organization: "mirroraculous"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - go get ./...

script:
  - go test -v -json ./... > report.json
  - go test -cover -coverprofile=coverage.out ./...
  - sonar-scanner
